# Generated by Django 5.2.11 on 2026-02-18 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient_portal', '0002_patientinvite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientinvite',
            name='token',
        ),
        migrations.AddField(
            model_name='patientinvite',
            name='email',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='patientinvite',
            name='invitation_code',
            field=models.CharField(blank=True, db_index=True, max_length=32, null=True, unique=True),
        ),
    ]
