# Generated by Django 5.2.11 on 2026-02-17 09:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('opd', 'OPD'), ('referred', 'Referred'), ('converted', 'Converted'), ('admitted', 'Admitted'), ('ongoing', 'Ongoing Treatment'), ('discharged', 'Discharged'), ('billing_received', 'Billing Received')], default='referred', max_length=20)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('suggested_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('suggested_sshs', models.CharField(blank=True, help_text='Suggested Super Specialty Hospitals', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referred_date', models.DateTimeField(blank=True, null=True)),
                ('converted_date', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('zoho_lead_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_deal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='authentication.clinic')),
            ],
        ),
        migrations.CreateModel(
            name='SharedPatientDocument',
            fields=[
                ('id', models.UUIDField(editable=False, primary_key=True, serialize=False)),
                ('patient_zoho_id', models.CharField(db_index=True, max_length=255)),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=50)),
                ('uploaded_at', models.DateTimeField()),
                ('s3_key', models.CharField(max_length=500)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('doctor_email', models.EmailField(db_index=True, max_length=254)),
                ('doctor_mobile', models.CharField(max_length=20)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Shared Patient Document',
                'verbose_name_plural': 'Shared Patient Documents',
                'db_table': 'shared_patient_documents',
                'indexes': [models.Index(fields=['doctor_email', 'is_active'], name='shared_pati_doctor__ca846c_idx'), models.Index(fields=['patient_zoho_id', 'is_active'], name='shared_pati_patient_0526ac_idx')],
            },
        ),
        migrations.CreateModel(
            name='SharedDocumentInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('risk_flags', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField()),
                ('shared_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='patients.sharedpatientdocument')),
            ],
            options={
                'verbose_name': 'Shared Document Insight',
                'verbose_name_plural': 'Shared Document Insights',
                'db_table': 'shared_document_insights',
                'indexes': [models.Index(fields=['shared_document'], name='shared_docu_shared__bc0cc4_idx')],
            },
        ),
    ]
