# Generated by Django 5.2.11 on 2026-02-18 05:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('s3_key', models.CharField(max_length=500)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('category', models.CharField(choices=[('Doctor Consultation', 'Doctor Consultation'), ('Lab Tests', 'Lab Tests'), ('Prescription', 'Prescription'), ('Imaging/Scan', 'Imaging/Scan'), ('Health Record', 'Health Record'), ('Others', 'Others')], default='Others', max_length=50)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('ai_processed', models.BooleanField(default=False)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='patients.patient')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PatientDocumentInsight',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('key_findings', models.JSONField(default=list)),
                ('risk_flags', models.JSONField(default=list)),
                ('tags', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='insight', to='patients.patientdocument')),
            ],
        ),
    ]
