# Generated by Django 5.2.11 on 2026-02-19 09:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_alter_user_role'),
        ('patients', '0002_patientdocument_patientdocumentinsight'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='converted_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='referred_date',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='revenue',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='suggested_specialty',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='suggested_sshs',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zoho_contact_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zoho_deal_id',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='zoho_lead_id',
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='opd', max_length=20),
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('zoho_lead_id', models.CharField(blank=True, db_index=True, max_length=100, null=True)),
                ('zoho_deal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('zoho_contact_id', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('referred', 'Referred'), ('converted', 'Converted'), ('admitted', 'Admitted'), ('ongoing', 'Ongoing Treatment'), ('discharged', 'Discharged'), ('billing_received', 'Billing Received')], default='referred', max_length=20)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('suggested_specialty', models.CharField(blank=True, max_length=255, null=True)),
                ('suggested_sshs', models.CharField(blank=True, help_text='Suggested Super Specialty Hospitals', max_length=255, null=True)),
                ('revenue', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('referred_date', models.DateTimeField(auto_now_add=True)),
                ('converted_date', models.DateTimeField(blank=True, null=True)),
                ('status_updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.clinic')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='patients.patient')),
            ],
            options={
                'ordering': ['-referred_date'],
            },
        ),
    ]
