# Generated by Django 5.2.11 on 2026-02-24 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_email_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner (Doctor)'), ('doctor', 'Doctor'), ('receptionist', 'Receptionist'), ('nurse', 'Nurse'), ('other', 'Other'), ('admin', 'Admin'), ('patient', 'Patient')], default='doctor', max_length=20),
        ),
    ]
