# Generated by Django 5.2.11 on 2026-02-25 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_user_age_in_years_user_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='custom_role',
            field=models.CharField(blank=True, default='', help_text="Custom role title when role is 'other'", max_length=50),
        ),
    ]
