# Generated by Django 5.2.11 on 2026-03-01 18:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_add_custom_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='mou_signed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='MOUAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(default='1.0', max_length=50)),
                ('hospital_name', models.CharField(max_length=255)),
                ('authorized_signatory_name', models.CharField(max_length=255)),
                ('hospital_address', models.TextField()),
                ('bank_account_number', models.CharField(blank=True, max_length=50)),
                ('bank_name', models.CharField(blank=True, max_length=255)),
                ('bank_branch', models.CharField(blank=True, max_length=255)),
                ('bank_ifsc', models.CharField(blank=True, max_length=20)),
                ('bank_address', models.TextField(blank=True)),
                ('professional_fee', models.CharField(blank=True, max_length=100)),
                ('signature_s3_key', models.CharField(max_length=500)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mou_agreements', to='authentication.clinic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mou_agreements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-signed_at'],
            },
        ),
    ]
