# Generated by Django 5.2.11 on 2026-02-17 09:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('shared_with_email', models.EmailField(db_index=True, max_length=254)),
                ('shared_with_mobile', models.CharField(blank=True, max_length=20)),
                ('document_title', models.CharField(max_length=255)),
                ('s3_key', models.CharField(max_length=500)),
                ('file_extension', models.CharField(max_length=10)),
                ('file_size', models.BigIntegerField(default=0)),
                ('shared_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('shared_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-shared_at'],
                'indexes': [models.Index(fields=['shared_with_email', 'is_active'], name='document_sh_shared__cd2841_idx')],
            },
        ),
    ]
